### ISSUE TITLE
Bug: Inline notation is getting cut off in sub-variations of Interactive Lessons in Studies.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#116] opened 2020-12-07 11:57 UTC
In a study I made, when promoting a pawn on 57, it does not say "P-57+" as one might expect. Instead, it says "5-7+", which does not make sense. Here is the study I saw the problem on: https://lishogi.org/study/PPWu7nJA

![image](https://user-images.githubusercontent.com/600562/101347528-161c9880-383f-11eb-9708-a31c985bd63e.png)

**Comment by WandererXII** [comment] 2020-12-07 21:20
I will be adding more notation styles this week, I rewritten how the notations are displayed and I can't reproduce this on my local machine. Therefore I think it will be fixed after I push the new update

**Comment by WandererXII** [comment] 2020-12-15 00:44
Seems to be solved, I know of some issues with Japanese notation ambiguity tho, so I will also have to fix that. But closing this, thanks for reporting this.

**Closed by WandererXII** 2020-12-15 00:44 UTC
