### ISSUE TITLE
advanced game search on user profile page broken

### ISSUE THREAD

**Issue by peanatsu** [WandererXII/lishogi#319] opened 2021-05-24 16:04 UTC
go to user profile page, click the "Games" tab, then click the "Advanced Search" sub-tab. This should display *all* games of the user (since no search criteria have been entered), but it displays "No game found".

If you enter search criteria it remains the same: it never seems to find any games.

edit: tested in chromium and firefox, though I hardly think this is a browser issue (more likely a database problem)

**Comment by justremember** [comment] 2021-05-24 16:22
Duplicate of https://github.com/WandererXII/lishogi/issues/206.

**Comment by peanatsu** [comment] 2021-05-24 16:39
sorry about that. I saw the issue beforehand, but I think I was confused because it doesnt decribe the problem at all. Maybe a bit more info in the message body would help (even if it just states "adanced game search and study search not working at all" or something to that effect)

Guess this issue can be closed then.

**Closed** 2021-05-24 16:43 UTC
Labels: duplicate
