### ISSUE TITLE
Typo: links in user profile still mention chess instead of shogi

### ISSUE THREAD

**Issue by Lishkon** [WandererXII/lishogi#46] opened 2020-11-18 15:33 UTC
Hi! I think this has just not been yet proofread or corrected when copying that from lichess.org, but few items still mention chess :)

**Steps to reproduce:**
1. Click on the user's name in the upper right corner and click on "Profile"
2. Observe the links in the "What now? Here are a few suggestions:" 

**Actual result:** first two links mention 'chess'
**Expected result:** 'shogi' is used instead of 'chess'

See it on the screenshot bellow:
![image](https://user-images.githubusercontent.com/3415689/99550884-e0189100-29c3-11eb-90ad-e1a380337c20.png)

**Comment by timezombi** [comment] 2020-11-18 22:12
This is a duplicate of Issue #22. I've noticed a lot of references to chess still in the code base as well!  This is probably the most visible. Did you notice any other instances of "chess" on the site where there should be "shogi" instead?

**Comment by WandererXII** [comment] 2020-11-19 00:03
I am slowly changing them, have some patience please, but from the wester standpoint one could even argue that shogi is Japanese chess, so it could be worse.

**Comment by WandererXII** [comment] 2020-11-19 21:53
Fixed!

**Closed by WandererXII** 2020-11-19 21:53 UTC

**Comment by Lishkon** [comment] 2020-11-20 17:20
And one more place just has been found. 
![image](https://user-images.githubusercontent.com/3415689/99829740-56082e00-2b65-11eb-91db-d3e08d135573.png)
The 'chess' is shown in the snippet when you share a link in a social media
![image](https://user-images.githubusercontent.com/3415689/99829820-789a4700-2b65-11eb-91ad-c20c99c7d1e2.png)

jfyi @WandererXII
